"""Extend DeliveryAddressDetailsModel

Revision ID: 14093d6710a8
Revises: 601d02bb839e
Create Date: 2022-08-21 02:00:06.710526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14093d6710a8'
down_revision = '601d02bb839e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_details', sa.Column('first_name', sa.String(length=64), nullable=False))
    op.add_column('delivery_details', sa.Column('last_name', sa.String(length=64), nullable=False))
    op.add_column('delivery_details', sa.Column('phone_number', sa.String(length=9), nullable=False))
    op.alter_column('delivery_details', 'holder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_details', 'holder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('delivery_details', 'phone_number')
    op.drop_column('delivery_details', 'last_name')
    op.drop_column('delivery_details', 'first_name')
    # ### end Alembic commands ###
