"""Modify OrderProductModel and added total price

Revision ID: 1aefef9a92ae
Revises: 3ac55a9de914
Create Date: 2022-08-28 00:02:37.187499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aefef9a92ae'
down_revision = '3ac55a9de914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total_price')
    # ### end Alembic commands ###
