"""Rename ForeignKey fields

Revision ID: 1b2917197359
Revises: 9dc4e688fc32
Create Date: 2022-08-19 01:15:05.743465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2917197359'
down_revision = '9dc4e688fc32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_details', sa.Column('holder_id', sa.Integer(), nullable=False))
    op.drop_constraint('customer_details_customer_id_key', 'customer_details', type_='unique')
    op.create_unique_constraint(None, 'customer_details', ['holder_id'])
    op.drop_constraint('customer_details_customer_id_fkey', 'customer_details', type_='foreignkey')
    op.create_foreign_key(None, 'customer_details', 'customer', ['holder_id'], ['id'])
    op.drop_column('customer_details', 'customer_id')
    op.add_column('delivery_details', sa.Column('holder_id', sa.Integer(), nullable=False))
    op.drop_constraint('delivery_details_customer_id_fkey', 'delivery_details', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_details', 'customer', ['holder_id'], ['id'])
    op.drop_column('delivery_details', 'customer_id')
    op.add_column('shop', sa.Column('holder_id', sa.Integer(), nullable=False))
    op.drop_constraint('shop_shop_owner_id_fkey', 'shop', type_='foreignkey')
    op.create_foreign_key(None, 'shop', 'shop_owner', ['holder_id'], ['id'])
    op.drop_column('shop', 'shop_owner_id')
    op.add_column('shop_owner_details', sa.Column('holder_id', sa.Integer(), nullable=False))
    op.drop_constraint('shop_owner_details_shop_owner_id_key', 'shop_owner_details', type_='unique')
    op.create_unique_constraint(None, 'shop_owner_details', ['holder_id'])
    op.drop_constraint('shop_owner_details_shop_owner_id_fkey', 'shop_owner_details', type_='foreignkey')
    op.create_foreign_key(None, 'shop_owner_details', 'shop_owner', ['holder_id'], ['id'])
    op.drop_column('shop_owner_details', 'shop_owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_owner_details', sa.Column('shop_owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shop_owner_details', type_='foreignkey')
    op.create_foreign_key('shop_owner_details_shop_owner_id_fkey', 'shop_owner_details', 'shop_owner', ['shop_owner_id'], ['id'])
    op.drop_constraint(None, 'shop_owner_details', type_='unique')
    op.create_unique_constraint('shop_owner_details_shop_owner_id_key', 'shop_owner_details', ['shop_owner_id'])
    op.drop_column('shop_owner_details', 'holder_id')
    op.add_column('shop', sa.Column('shop_owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shop', type_='foreignkey')
    op.create_foreign_key('shop_shop_owner_id_fkey', 'shop', 'shop_owner', ['shop_owner_id'], ['id'])
    op.drop_column('shop', 'holder_id')
    op.add_column('delivery_details', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'delivery_details', type_='foreignkey')
    op.create_foreign_key('delivery_details_customer_id_fkey', 'delivery_details', 'customer', ['customer_id'], ['id'])
    op.drop_column('delivery_details', 'holder_id')
    op.add_column('customer_details', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customer_details', type_='foreignkey')
    op.create_foreign_key('customer_details_customer_id_fkey', 'customer_details', 'customer', ['customer_id'], ['id'])
    op.drop_constraint(None, 'customer_details', type_='unique')
    op.create_unique_constraint('customer_details_customer_id_key', 'customer_details', ['customer_id'])
    op.drop_column('customer_details', 'holder_id')
    # ### end Alembic commands ###
