"""Added more fields to OrderModel

Revision ID: 1eec6d5ed9d0
Revises: 3f170de5b381
Create Date: 2022-08-27 20:45:58.252524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eec6d5ed9d0'
down_revision = '3f170de5b381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('online', 'cache', name='paymentmethod'), nullable=False),
    sa.Column('payed', sa.Boolean(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_products',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.Column('order_quantity', sa.Float(), nullable=False),
    sa.Column('order_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_products')
    op.drop_table('order')
    # ### end Alembic commands ###
