"""Add Enum ProductCategories and delete category from shopModel

Revision ID: 1f2e4264dc9f
Revises: 220813adf3cf
Create Date: 2022-08-22 20:39:13.373228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2e4264dc9f'
down_revision = '220813adf3cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('value', sa.String(length=64), nullable=False))
    op.drop_constraint('shop_category_id_fkey', 'shop', type_='foreignkey')
    op.drop_column('shop', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('shop_category_id_fkey', 'shop', 'category', ['category_id'], ['id'])
    op.drop_column('category', 'value')
    # ### end Alembic commands ###
