"""Rename field in ShopModel

Revision ID: 220813adf3cf
Revises: 14093d6710a8
Create Date: 2022-08-22 19:34:03.458554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220813adf3cf'
down_revision = '14093d6710a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('verified', sa.Boolean(), nullable=False))
    op.drop_column('shop', 'confirm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('confirm', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('shop', 'verified')
    # ### end Alembic commands ###
