"""Add active field in ShopModel

Revision ID: 296f696ede5c
Revises: 6fd2edd0b97e
Create Date: 2022-08-23 02:37:39.036057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296f696ede5c'
down_revision = '6fd2edd0b97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'active')
    # ### end Alembic commands ###
