"""Alter field name in ShopModel

Revision ID: 326753047981
Revises: 63c5e6291116
Create Date: 2022-08-22 20:45:06.801932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326753047981'
down_revision = '63c5e6291116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('verifying_documents_image_url', sa.String(length=255), nullable=False))
    op.drop_column('shop', 'confirm_documents_image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('confirm_documents_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('shop', 'verifying_documents_image_url')
    # ### end Alembic commands ###
