"""Modify OrderProductModel

Revision ID: 3ac55a9de914
Revises: 1eec6d5ed9d0
Create Date: 2022-08-27 23:03:16.020408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac55a9de914'
down_revision = '1eec6d5ed9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('order_id', sa.Integer(), nullable=False))
    op.add_column('order_products', sa.Column('product_id', sa.Integer(), nullable=False))
    op.drop_constraint('order_products_right_id_fkey', 'order_products', type_='foreignkey')
    op.drop_constraint('order_products_left_id_fkey', 'order_products', type_='foreignkey')
    op.create_foreign_key(None, 'order_products', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'order_products', 'order', ['order_id'], ['id'])
    op.drop_column('order_products', 'right_id')
    op.drop_column('order_products', 'left_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('left_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('order_products', sa.Column('right_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_products', type_='foreignkey')
    op.drop_constraint(None, 'order_products', type_='foreignkey')
    op.create_foreign_key('order_products_left_id_fkey', 'order_products', 'order', ['left_id'], ['id'])
    op.create_foreign_key('order_products_right_id_fkey', 'order_products', 'product', ['right_id'], ['id'])
    op.drop_column('order_products', 'product_id')
    op.drop_column('order_products', 'order_id')
    # ### end Alembic commands ###
