"""Added stripe price and product id to ProductModel

Revision ID: 3f170de5b381
Revises: 6728f07778ad
Create Date: 2022-08-27 00:12:25.333136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f170de5b381'
down_revision = '6728f07778ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('stripe_price_id', sa.String(length=255), nullable=True))
    op.add_column('product', sa.Column('stripe_product_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'product', ['stripe_product_id'])
    op.create_unique_constraint(None, 'product', ['stripe_price_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'stripe_product_id')
    op.drop_column('product', 'stripe_price_id')
    # ### end Alembic commands ###
