"""Added ProductModel

Revision ID: 52fb2f0ff7e9
Revises: 296f696ede5c
Create Date: 2022-08-24 00:46:58.839859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52fb2f0ff7e9'
down_revision = '296f696ede5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('clothing', 'shoes', 'electronics', 'books', 'games', 'cosmetics', 'accessories', 'food', 'appliances', 'furniture', 'sport', 'toys', 'gardens', 'pets', name='productcategories'), nullable=False),
    sa.Column('registered_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.Column('holder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['holder_id'], ['shop_owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
