"""Move verified from ShopOwnerModel to ShopOwnerDetailsModel

Revision ID: 601d02bb839e
Revises: 0752bcc9d8d3
Create Date: 2022-08-21 01:39:55.279874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601d02bb839e'
down_revision = '0752bcc9d8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_owner', 'confirmed')
    op.add_column('shop_owner_details', sa.Column('verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_owner_details', 'verified')
    op.add_column('shop_owner', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
