"""Added image url to product.

Revision ID: 6728f07778ad
Revises: c184284fa3e4
Create Date: 2022-08-26 14:44:56.596461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6728f07778ad'
down_revision = 'c184284fa3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_image_url')
    # ### end Alembic commands ###
