"""Create ShopModel

Revision ID: 8161bf9d5ce8
Revises: 253959058ec6
Create Date: 2022-08-17 01:35:14.934844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8161bf9d5ce8'
down_revision = '253959058ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('bulstat', sa.String(length=9), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=9), nullable=True),
    sa.Column('confirm_documents', sa.String(length=255), nullable=False),
    sa.Column('confirm', sa.Boolean(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.Column('shop_owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_owner_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop')
    # ### end Alembic commands ###
