"""Unify image_urls

Revision ID: 88093a8f3714
Revises: 1b2917197359
Create Date: 2022-08-19 13:39:30.937877

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '88093a8f3714'
down_revision = '1b2917197359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_details', sa.Column('profile_picture_image_url', sa.String(length=255), nullable=True))
    op.drop_column('customer_details', 'profile_picture_url')
    op.add_column('shop', sa.Column('brand_logo_image_url', sa.String(length=255), nullable=True))
    op.add_column('shop', sa.Column('confirm_documents_image_url', sa.String(length=255), nullable=False))
    op.drop_column('shop', 'confirm_documents')
    op.add_column('shop_owner', sa.Column('confirm', sa.Boolean(), nullable=False))
    op.add_column('shop_owner_details', sa.Column('profile_picture_image_url', sa.String(length=255), nullable=True))
    op.add_column('shop_owner_details',
                  sa.Column('confirm_identity_documents_image_url', sa.String(length=255), nullable=False))
    op.drop_column('shop_owner_details', 'profile_picture_url')
    op.drop_column('shop_owner_details', 'confirm')
    op.drop_column('shop_owner_details', 'confirm_identity_documents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_owner_details',
                  sa.Column('confirm_identity_documents', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('shop_owner_details', sa.Column('confirm', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('shop_owner_details',
                  sa.Column('profile_picture_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('shop_owner_details', 'confirm_identity_documents_image_url')
    op.drop_column('shop_owner_details', 'profile_picture_image_url')
    op.drop_column('shop_owner', 'confirm')
    op.add_column('shop', sa.Column('confirm_documents', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('shop', 'confirm_documents_image_url')
    op.drop_column('shop', 'brand_logo_image_url')
    op.add_column('customer_details',
                  sa.Column('profile_picture_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('customer_details', 'profile_picture_image_url')
    # ### end Alembic commands ###
