"""Make show_owner_id unique

Revision ID: 9dc4e688fc32
Revises: ba173314be50
Create Date: 2022-08-18 22:49:31.354570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc4e688fc32'
down_revision = 'ba173314be50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'shop_owner_details', ['shop_owner_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_owner_details', type_='unique')
    # ### end Alembic commands ###
