"""Edit shop_owner_id un shopModel

Revision ID: ba173314be50
Revises: c10ac74b1337
Create Date: 2022-08-17 14:09:14.738401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba173314be50'
down_revision = 'c10ac74b1337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shop_shop_owner_id_fkey', 'shop', type_='foreignkey')
    op.create_foreign_key(None, 'shop', 'shop_owner', ['shop_owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop', type_='foreignkey')
    op.create_foreign_key('shop_shop_owner_id_fkey', 'shop', 'customer', ['shop_owner_id'], ['id'])
    # ### end Alembic commands ###
