"""Edit shop_owner_id

Revision ID: c10ac74b1337
Revises: d2fa97704e3a
Create Date: 2022-08-17 14:07:24.239371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10ac74b1337'
down_revision = 'd2fa97704e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shop_owner_details_shop_owner_id_fkey', 'shop_owner_details', type_='foreignkey')
    op.create_foreign_key(None, 'shop_owner_details', 'shop_owner', ['shop_owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_owner_details', type_='foreignkey')
    op.create_foreign_key('shop_owner_details_shop_owner_id_fkey', 'shop_owner_details', 'customer', ['shop_owner_id'], ['id'])
    # ### end Alembic commands ###
