"""Added field to ProductModel

Revision ID: c184284fa3e4
Revises: 3e8bc0156366
Create Date: 2022-08-25 01:13:06.913007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c184284fa3e4'
down_revision = '3e8bc0156366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('listed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'listed')
    # ### end Alembic commands ###
