"""Alter BaseDetails profile_picture to profile_picture_url

Revision ID: d2fa97704e3a
Revises: f9eb6c874798
Create Date: 2022-08-17 13:49:54.617346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2fa97704e3a'
down_revision = 'f9eb6c874798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_details', sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
    op.drop_column('customer_details', 'profile_picture')
    op.add_column('shop_owner_details', sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
    op.drop_column('shop_owner_details', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_owner_details', sa.Column('profile_picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('shop_owner_details', 'profile_picture_url')
    op.add_column('customer_details', sa.Column('profile_picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('customer_details', 'profile_picture_url')
    # ### end Alembic commands ###
