"""Create CategoryModel

Revision ID: f9eb6c874798
Revises: 8161bf9d5ce8
Create Date: 2022-08-17 12:23:01.094786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9eb6c874798'
down_revision = '8161bf9d5ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('shop', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('shop', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shop', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop', type_='foreignkey')
    op.drop_column('shop', 'category_id')
    op.drop_column('shop', 'description')
    op.drop_table('category')
    # ### end Alembic commands ###
